env:
  browser: true
  node: true
  jquery: true
extends: 'eslint:recommended'
globals:
  d3: true
  emoViz: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - warn
  no-unused-vars:
    - warn
